ALTER TABLE invoices DROP COLUMN IF EXISTS medidas;
ALTER TABLE invoices DROP COLUMN IF EXISTS material;
ALTER TABLE invoices DROP COLUMN IF EXISTS pintura;
ALTER TABLE invoices DROP COLUMN IF EXISTS color;
ALTER TABLE invoices DROP COLUMN IF EXISTS laqueado;
ALTER TABLE invoices DROP COLUMN IF EXISTS cogs_amount;
